# Use root/example as user/password credentials
version: '3.3'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'snippetbox'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'web'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080